baseURL = "/"
title = "Hill Country Car Culture Magazine"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"

[params]
fancyTitle = "Texas Hill Country Car Culture" # title for frontpage, may include image
copyright = "population2.com - Louis Beaumier III - Hill Country Car Culture"
description = 'A Magazine celebrating car culture in the Texas Hill Country.'
startbuttonText = "Subscribe Now"
startbuttonLink = "#"

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/posts/'
title = "Posts"

[params.one]
enable = true
title = 'About the Magazine'
body = 'Hill Country Car Culture is distributed bi-monthly and complimentary. It is available at local car shops, at shows and by subscription for the cost of postage only. Cars shows and shops, vintage, classic and antique restorations, hot rods and muscle cars are covered. Even some motorcycles and older foreign cars.'

[[params.one.icon]]
icon = "fa-car"
style = "1"
label = "Lorem"

[[params.one.icon]]
icon = "fa-motorcycle"
style = "2"
label = "Ipsum"

[[params.one.icon]]
icon = "fa-truck"
style = "3"
label = "Dolor"

[params.two]
enable = true

[[params.two.section]]
img = "images/pic17.jpg"
title = 'Classic Texas Hot Rods'
body = 'Covering Cars shows and shops, vintage, classic and antique restorations, hot rods and muscle cars are covered.'

[[params.two.section]]
img = "images/pic11.jpg"
title = 'Hill Country Views'
body = 'Check us out available at local car shops, at shows and by subscription for the cost of postage only.'

[[params.two.section]]
img = "images/pic18.jpg"
title = 'Each bi-monthly and complimentary issue is also packed with'
body = '<li>Farm to Market Classfied Ads!</li><li> Car Stories!</li><li>Upcoming Event Information!</li>'

[params.three]
enable = true
title = 'Our Sponsors'
body = 'Published free in the Hill Country area thanks to these fine shops ans sponsors.'

[[params.three.feature]]
icon = "facebook fa-car"
title = "Murphos Rods and Customs"
body = "Custom Car Restoration and Hot Rod Shop with a custom lifestyle boutique."
link = "https://www.murphos.com/"

[[params.three.feature]]
icon = "fa-laptop"
title = "That Cool A/C Shop"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-code"
title = "Foo bar"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-headphones"
title = "Baz kram"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-heart-o"
title = "Some latin text"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-flag-o"
title = "Nothing important"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[params.cta]
enable = true
title = "Follow us on Facebook and Instagram"
body = "Find the latest on Hill Country Car culture by following us on social media."

[[params.cta.link]]
href = "https://www.facebook.com/hillcountrycarculture/"
text = "Facebook"
special = true

[[params.cta.link]]
href = "https://www.instagram.com/hillcountrycarculture/"
text = "Instagram"
special = false

[params.contact]
enable = true
title = "Contact the Magazine"
body = "Leave us a message below and we'll be in touch!"
phone = " (000 000 0000"
address = "1234 Some Tx Road<br />Some Place, Some State 0000<br />Some Country"
email = "email@hillcountrycarmagazine.com"
subject = "New Submission!"
plain = false

[params.social]
twitter = ""
facebook = "https://www.facebook.com/hillcountrycarculture/"
instagram = "https://www.instagram.com/hillcountrycarculture/"
dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"
